stages:
    data_ingestion:
      cmd: python src/datafile/data_ingestion.py
      deps:
      - src/datafile/data_ingestion.py
      outs: 
      - data/external
    data_splitting:
      cmd: python src/datafile/data_splitting.py
      deps:
      - data/external
      - src/datafile/data_splitting.py
      params:
      - data_splitting.test_size
      outs:
      - data/raw
    data_preprocessing:
      cmd: python src/datafile/data_preprocessing.py
      deps:
      - src/datafile/data_ingestion.py
      - data/raw
      outs:
      - data/processed
    feature_engineering:
      cmd: python src/features/feature_engineering.py
      deps:
      - data/processed
      - src/features/feature_engineering.py
      params:
      - feature_engineering.max_features
     
      outs:
      - data/features
      - models/vectorizer.pkl

    model_building:
      cmd: python src/model/model_building.py
      deps:
      - data/features
      - src/model/model_building.py
      params:
      - model_building.learning_rate
      - model_building.n_estimators
      outs:
      - models/model.pkl
    model_evaluation:
      cmd: python src/model/model_evaluation.py
      deps:
      - models
      - src/model/model_evaluation.py
      outs:
      - reports/experiment_info.json
    register_model:
      cmd: python src/model/register_model.py
      deps:
        - reports/experiment_info.json
        - src/model/register_model.py
# name:
# CMD
